name: AdvancedBow
main: shadowlauch.advancedbow.main.AdvancedBow
version: 0.1
commands:
    advancedbow:
        description: AdvancedBow Command
        usage: /<command> <version/reload/help/fire/explosive>
        aliases: [ab,bow]